apiVersion: v1
kind: Service
metadata:
  name: svc-globoticket-services-order
  labels:
    version: dev
    product: globoticket-services-order
spec:
  selector:
    app: globoticket-services-order
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 
      name: http   
    - port: 443
      targetPort: 443
      protocol: TCP 
      name: https  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globoticket-services-order 
spec:
  selector:
    matchLabels:
      app: globoticket-services-order
  replicas: 1
  template:
    metadata:
      labels:
        app: globoticket-services-order
    spec:
      containers:
      - name: globoticket-services-order
        image: azmcggloboticketacr.azurecr.io/globoticket.services.ordering:1        
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: ServiceBusConnectionString
            value: Endpoint=sb://globoticket.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Hi0hqUzgNIhGOcceT/gW4B23fHSlbVM+FPAxjq3zZTc=
          - name: CheckoutMessageTopic
            value: checkoutmessage
          - name: OrderPaymentRequestMessageTopic
            value: orderpaymentrequestmessage
          - name: OrderPaymentUpdatedMessageTopic
            value: orderpaymentupdatedmessage
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
               name: ordering-db
               key: connectionstring      
        ports:
        - containerPort: 80
        - containerPort: 443
      imagePullSecrets:
        - name: acr-secret
