apiVersion: v1
kind: Service
metadata:
  name: svc-globoticket-services-discount
  labels:
    version: dev
    product: globoticket-services-discount
spec:
  selector:
    app: globoticket-services-discount
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 
      name: http   
    - port: 443
      targetPort: 443
      protocol: TCP 
      name: https  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globoticket-services-discount 
spec:
  selector:
    matchLabels:
      app: globoticket-services-discount
  replicas: 1
  template:
    metadata:
      labels:
        app: globoticket-services-discount
    spec:
      containers:
      - name: globoticket-services-discount
        image: morcodou/globoticket.services.discount:latest        
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
               name: discount-db
               key: connectionstring      
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        - containerPort: 443

