apiVersion: v1
kind: Service
metadata:
  name: svc-globoticket-services-shoppingbasket
  labels:
    version: dev
    product: globoticket-services-shoppingbasket
spec:
  selector:
    app: globoticket-services-shoppingbasket
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 
      name: http   
    - port: 443
      targetPort: 443
      protocol: TCP 
      name: https  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globoticket-services-shoppingbasket 
spec:
  selector:
    matchLabels:
      app: globoticket-services-shoppingbasket
  replicas: 1
  template:
    metadata:
      labels:
        app: globoticket-services-shoppingbasket
    spec:
      containers:
      - name: globoticket-services-shoppingbasket
        image: morcodou/globoticket.services.shoppingbasket:latest        
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: ApiConfigs__EventCatalog__Uri
            value: http://svc-globoticket-services-eventcatalog
          - name: ApiConfigs__Discount__Uri
            value: http://svc-globoticket-services-discount
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
               name: shoppingbasket-db
               key: connectionstring      
        ports:
        - containerPort: 80
        - containerPort: 443

