apiVersion: v1
kind: Service
metadata:
  name: svc-globoticket-web
  labels:
    version: dev
    product: globoticket-web
spec:
  selector:
    app: globoticket-web
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 
      name: http   
      nodePort: 30080
    - port: 443
      targetPort: 443
      protocol: TCP 
      name: https  
      nodePort: 30443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globoticket-web 
spec:
  selector:
    matchLabels:
      app: globoticket-web
  replicas: 1
  template:
    metadata:
      labels:
        app: globoticket-web
    spec:
      containers:
      - name: globoticket-web
        image: morcodou/globoticket.web:latest        
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: ApiConfigs__EventCatalog__Uri
            value: http://svc-globoticket-services-eventcatalog
          - name: ApiConfigs__ShoppingBasket__Uri
            value: http://svc-globoticket-services-shoppingbasket
          - name: ApiConfigs__Order__Uri
            value: http://svc-globoticket-services-order
          - name: ApiConfigs__Marketing__Uri
            value: http://svc-globoticket-services-marketing
          - name: ApiConfigs__Discount__Uri
            value: http://svc-globoticket-services-discount
        ports:
        - containerPort: 80
        - containerPort: 443

