name: globoticket.services.shoppingbasket

on:
  push:
    branches: [ containarized_aks_allup ]
    paths:
    - 'GloboTicket/GloboTicket.Services.ShoppingBasket/**'
    - 'GloboTicket/aks-globoticket.services.shoppingbasket.yaml'
  pull_request:
    branches: [ containarized_aks_allup ]
    paths:
    - 'GloboTicket/GloboTicket.Services.ShoppingBasket/**'
    - 'GloboTicket/aks-globoticket.services.shoppingbasket.yaml'
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      imageRepository: 'globoticket.services.shoppingbasket'
      containerRegistry: 'globoticketacr.azurecr.io'
      dockerfilePath: 'GloboTicket/GloboTicket.Services.ShoppingBasket/Dockerfile'
      deploymentFile: 'aks-globoticket.services.shoppingbasket.yaml'
      trivyVersion: 0.12.0
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.containerRegistry }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}
    
    - name: Build an image from Dockerfile
      run: |
        docker build -t ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}} -f ${{env.dockerfilePath}} ${{github.workspace}}/GloboTicket

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'MEDIUM,CRITICAL,HIGH'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'

    - name: push image to ACR
      run: |
        docker push ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}

    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:
        files: ${{github.workspace}}/GloboTicket/${{env.deploymentFile}}
      env: 
        Build.BuildId: ${{github.run_number}}
    
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.KUBECONFIG}} 
      id: setcontext
    
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
            ${{github.workspace}}/GloboTicket/${{env.deploymentFile}}